<p><?php print $intro_text; ?></p>
<div class="register-form-container">
    <?php print $rendered; ?>
    <div id="terms" style="display:none; max-width: 600px; max-height: 600px; text-align:left; color: #FFF;">
        <h1>Terms of Use</h1>
        <p>The services that mnartists.org provides are subject to the following terms of use.</p>
        <p>This website ("www.mnartists.org") is provided as a public service by mnartists.org, a Minnesota non-profit corporation. Please read the following text that describes the terms of use for mnartists.org. If you choose to use the mnartists.org site or any services provided through the site, you agree that these terms apply to your use.</p>
        <h2>Your Participation in mnartists.org</h2>
        <p>In order to register with mnartists.org and be entered into its directory of Minnesota artists and arts organizations, you must complete the registration process by providing us with information as prompted by the registration forms. You agree that the information you are providing us is accurate as of the time you enter it. You also agree to tell us if your information should change. As part of this process you will obtain a user ID for mnartists.org and choose a password. You are responsible for maintaining the confidentiality of your user ID and password, and you agree that you are responsible for what might happen if another person should use your user ID.</p>
        <p>Your membership is provided at no charge to you. However, mnartists.org reserves the right to charge you for additional services you may choose to order from mnartists.org. Both you and mnartists.org have the right to terminate your membership and/or user account at any time, with or without reason. If mnartists.org wishes to terminate your account, mnartists.org will attempt once to send email to your last-known email address, advising you of the termination. If you wish to terminate your membership, you agree to send email or some other written notice to mnartists.org, using the then current contact information listed on the mnartists.org site.</p>
        <h2>Your Privacy</h2>
        <p>mnartists.org will only use your contact information (including your email address) to contact you about administrative issues concerning your membership. It will not be given to any other organizations. However, your email address will obviously be visible to anyone who views the site. Your email may also be used to mail you additional information if you select this option in the sign-up process or at a later date.</p>
        <h2>Links to Third Party Sites</h2>
        <p>mnartists.org may contain links to third party websites. These sites are not under the control of mnartists.org, and mnartists.org is not responsible for the contents of the linked sites.</p>
        <h2>Content</h2>
        <p>mnartists.org includes statements, graphics, and other content of third parties. mnartists.org is not responsible for screening, monitoring, or verifying such content, including with respect to such content's accuracy, reliability, or compliance with copyright and other laws. mnartists.org reserves the right, but does not have the obligation, to edit or remove any material from the site at any time.</p>
        <p>The mnartists.org site may provide contact information concerning particular artists, and those artists may also offer to sell you goods or services. Any dealings you have with these artists are solely between you and the artist, and neither mnartists.org, the Walker Art Center, nor the McKnight Foundation have any responsibility for the results you may obtain from your dealings with the artists.</p>
        <p>As an artist or organization registering with mnartists.org, you agree that you will not use mnartists.org to post or display any material that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable to a reasonable person.</p>
        <h2>Submissions</h2>
        <p>mnartists.org allows you to post digitized representations of your work for display on the site. You must own all rights to any material that you submit, including the copyright. If you have the right to post works copyrighted by another person, you must include with your submission a statement describing where you obtained the work and that you have permission from the copyright owner to post the work on mnartists.org. Also, you shall not post any works that contain images or names of other people unless you have obtained a written release from all of those people that permits the display of the work on mnartists.org. If you need assistance in obtaining forms or in obtaining legal advice on how you can get the proper permissions and releases discussed in this paragraph, please contact artist services at Springboard for the Arts, http://www.springboardforthearts.org, .</p>
        <p>By posting textual information and images to mnartists.org, you are permitting mnartists.org to use your information and images in activities related to this website.</p>
        <p>DMCA Copyright Agent<br />
           Pursuant to Title 17, United States Code, Section 5121(c)(2), notifications of claimed copyright infringement for any materials posted or displayed on the mnartists.org site should be in writing, comply with the terms set forth in the statute, and sent exclusively to mnartists.org's designated agent: Project Director<br />
           mnartists.org<br />
           Walker Art Center<br />
           1750 Hennepin Avenue<br />
           Minneapolis, MN 55403
        </p>
        <h2>Amendments to These Terms of Use</h2>
        <p>We may change the terms and conditions under which the mnartists.org services and site are offered. We will make these changes by posting them on this page. Your use after that time will be governed by the then-current terms of use. We also may, from time to time, condition your ability to enter the site under your user ID and password by requiring you to show your agreement to the then-current terms of use.</p>
        <h2>Disclaimer of Warranty, Limitation of Liability</h2>
        <p>NEITHER MNARTISTS.ORG, THE WALKER ART CENTER, THE MCKNIGHT FOUNDATION, NOR ANY OF THEIR DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, OR REPRESENTATIVES (COLLECTIVELY THE "MNARTISTS.ORG PARTIES"), REPRESENT OR WARRANT THE ACCURACY, RELIABILITY, TIMELINESS OR COMPLETENESS OF ANY MATERIAL ON OR ACCESSIBLE THROUGH MNARTISTS.ORG, OR THAT THE SAME IS NON-DEFAMATORY, NON-INFRINGING OF COPYRIGHT OR OTHER THIRD PARTY RIGHTS, OR LAWFUL. THE MNARTISTS.ORG PARTIES EXPRESSLY DISCLAIM ANY WARRANTIES, EXPRESS OR IMPLIED, IN THE MATERIALS DISPLAYED ON THE MNARTISTS.ORG SITE, INCLUDING ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSE, OR ACCURACY OF THE INFORMATION CONTAINED IN THE SITE. ANY RELIANCE ON OR USE OF SUCH MATERIAL SHALL BE AT THE USER'S SOLE RISK.</p>
        <p>IN NO EVENT SHALL THE MNARTISTS.ORG PARTIES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES, OR ANY OTHER DAMAGES EXCEEDING AN AGGREGATE AMOUNT OF $10, WHICH ARISE OUT OF THE MNARTISTS.ORG WEBSITE, ITS USE OR INABILITY TO USE THE SITE.</p>
        <h2>Choice of Law, Venue</h2>
        <p>These terms of use are governed by and shall be interpreted under the laws of the State of Minnesota, without regard for its choice of law provisions. Any controversy, claim, or lawsuit which either you or mnartists.org might choose to bring against the other that concern mnartists.org or the mnartists.org site shall be heard exclusively in the federal or state courts located within Hennepin County, Minnesota, each of us agrees that these courts shall have personal jurisdiction over us, and we agree to waive any defenses or claims concerning personal jurisdiction or inconvenient forum.</p>
    </div>
</div>
