<?php

/**
 * @file
 * Code for the MNArtist Filters feature.
 */

function mnartist_filter_menu() {
	$items['mnartist/filter/submit'] = array(
		'page callback' => 'mnartist_filter_view',
		'access callback' => 'user_is_logged_in'
	);
    $items['user/saved-filters'] = array(
        'page callback' => 'mnartist_filter_user_view',
        'access callback' => 'user_is_logged_in'
    );
    $items['user/saved-filters/rename'] = array(
        'page callback' => 'mnartist_filter_rename',
        'access callback' => 'user_is_logged_in'
    );
    $items['user/saved-filters/delete'] = array(
        'page callback' => 'mnartist_filter_user_delete_filter',
        'access callback' => 'user_is_logged_in'
    );
	return $items;
}
function mnartist_filter_view()
{
	global $user;

	$data = array(
  		'uid' => $user->uid,
  		'title' => $_POST['name'],
  		'url' => urlencode($_POST['url']),
	);
	drupal_write_record('mnartist_filter', $data);
	header('Location: ' . $_POST['url']);
}

function mnartist_filter_user_delete_filter()
{
    global $user;
    $url = $_SERVER['REQUEST_URI'];
    $url = parse_url($url);
    if(isset($url['query']))
    {
        parse_str($url['query'], $vars);
        if(isset($vars['fid']))
        {
            $result = db_query("SELECT mn.fid, mn.uid, mn.title, mn.url FROM {mnartist_filter} mn WHERE mn.fid = :uid", array(':uid' => $vars['fid']))->fetchAssoc();
            if($result['uid'] == $user->uid)
            {
                $deleted = db_delete('mnartist_filter')->condition('uid', $user->uid)->condition('fid', $vars['fid'])->execute();
            }
        }
    }
    header('Location: /user/saved-filters');// @TODO this should be a drupal_goto

}

function mnartist_filter_user_view()
{
    if($_SERVER['REQUEST_URI'] == '/user/saved-filters')
    {
        global $user;

        ctools_add_js('filter', 'mnartist_filter');

        $result = db_query("SELECT mn.fid, mn.title, mn.url FROM {mnartist_filter} mn WHERE mn.uid = :uid", array(':uid' => $user->uid));
        $results = db_select('node', 'n')->fields('n', array('nid', 'title'))->condition('type', 'community')->execute()->fetchAll();

        $template_results = array();

        $menu = array();
        foreach($results as $row)
        {
            $menu[$row->nid] = $row->title;
        }
        while ($row = $result->fetchAssoc())
        {
            $context_row = new StdClass();

            $url = parse_url(urldecode($row['url']));
            $string = '';
            if(isset($url['query']))
            {
                parse_str($url['query'],$vars);
                if(isset($vars['og']))
                {
                    $string .= "<b>Communities: </b>";
                    foreach($vars['og'] as $mkey => $mvalue)
                    {
                        $string .= '<b>' . $menu[$mkey] . '</b>';
                        if(is_array($mvalue))
                        {
                            $string .= ': ';
                            $subm = array();
                            foreach($mvalue as $skey => $svalue)
                            {
                                $term = taxonomy_term_load($svalue);
                                if(isset($term->name))
                                {
                                    $subm[] = $term->name;
                                }

                            }
                            $string .= implode(', ', $subm);
                        }
                        $string .= " ";
                    }
                }

                if(isset($vars['og']) && isset($vars['content'])) $string .= '<br>';
                
                if(isset($vars['content']))
                {
                   	foreach($vars['content'] as $mkey => $mvalue)
                    {
                        $string .= '<b>';
                        if ($mkey == 'opportunity') {
                        	$string .= 'Opportunities';
                        } elseif (substr($mkey, -1) == 's') {
                        	$string .= ucfirst($mkey);
                        } else {
                        	$string .= ucfirst($mkey) . 's';
                        }
                        $string .= '</b> ';
                        if(is_array($mvalue))
                        {
                        	$string .= ': ';
                            $subm = array();
                            foreach($mvalue as $skey => $svalue)
                            {
                                $term = taxonomy_term_load($svalue);
                                if(isset($term->name))
                                {
                                    $subm[] = $term->name;
                                }

                            }
                            $string .= implode(', ', $subm);
                        }
                        $string .= " ";
                    }
                }
            } else {
                $string = '<b>All Communites</b>';
            }

            $context_row->communities_fragment = $string;
            $context_row->fid = $row['fid'];
            $context_row->title = $row['title'];
            $context_row->url = $row['url'];
            $template_results[] = $context_row;
        }
        return theme('mnartist_filter_saved_filters', array(
                        'filters' => $template_results,
                    ));
    }

}

function mnartist_filter_rename() {
    if (isset($_POST['fid']) && isset($_POST['newtitle'])) {
        $target_fid = $_POST['fid'];
        $newtitle = $_POST['newtitle'];
        $result = db_update('mnartist_filter')->fields(array('title' => $newtitle))->condition('fid', $target_fid, '=')->execute();

        if ($result === 1) {
            drupal_set_message("Filter title updated.");
        }
    }
    header('Location: /user/saved-filters');
}

function _mnartist_filter_block_visibility() {

    if(arg(0) == 'community' && user_is_logged_in())
    {
    	return true;
    } else {
    	return false;
    }
}

function mnartist_filter_block_info() {
    return array(
        'mna_filter_create' => array(
            'info' => 'MNArtist Create Filter',
            'cache' => DRUPAL_NO_CACHE,
            'visibility' => BLOCK_VISIBILITY_PHP,
            'pages' => '<?php return _mnartist_filter_block_visibility(); ?>'
        ),
/*
        'mna_filter_view' => array(
            'info' => t('MNArtist View Filters'),
            'cache' => DRUPAL_NO_CACHE,
            'visibility' => BLOCK_VISIBILITY_PHP,
            'pages' => '<?php return _mnartist_filter_profile_block_visibility(); ?>'
        )
        */
    );
}

function mnartist_filter_block_view($delta = '') {
    switch($delta) {
        case 'mna_filter_create':
            $block['content'] = _mnartist_filter_create_filter();
        break;
        /*
        case 'mna_filter_view':
            $block['subject'] = 'View Filter';
            $block['content'] = _mnartist_filter_view_filter();
        break;
        */
    }
    return $block;
}

function mnartist_filter_theme()
{
    return array(
        'mnartist_filter_saved_filters' => array(
            'variables' => array(),
            'template' => 'templates/mna-saved-filters',
        )
    );
}

function _mnartist_filter_create_filter()
{
    global $user;
    $url = urlencode($_SERVER['REQUEST_URI']);
    $result = db_query("SELECT mn.fid FROM {mnartist_filter} mn WHERE mn.uid = :uid AND mn.url = :url", array(':uid' => $user->uid, ':url' => $url));
    $record = $result->fetchAssoc();
	ctools_add_js('filter', 'mnartist_filter');
	ctools_add_css('filter', 'mnartist_filter');
	$output = '';
	$output .= '<div id="dialog-form" title="Create new filter">';
		$output .= '<p class="validateTips">Save your favorite filters and searches to bookmark and store the content that most interests you.</p>';

		$output .= '<form id="filter-form" action="/mnartist/filter/submit" method="post">';
		$output .= '<fieldset>';
		    $output .= '<label for="name">Filter Name</label>';
		    $output .= '<input type="text" name="name" id="name" class="text ui-widget-content ui-corner-all" /><br/>';
		    $output .= '<input type="hidden" name="url" value="' . $_SERVER['REQUEST_URI'] . '" />';
		$output .= '</fieldset>';
		$output .= '</form>';
	$output .= '</div>';
    $output .= "<ul class='menu'>";
        $output .= "<li class='first'><a class='star-link";
        if(isset($record['fid']))
        {
            $output .= " active";
        }
        $output .= "'><img src='".drupal_get_path('theme', 'mnartists')."/images/fav-star.svg' class='star-icon' /></a>";
        $output .= "<ul>";
            $output .= "<li><a href='#' id='create-new-filter'>Save this Filter</a></li>";
            $output .= "<hr />";
            $output .= "<li><a href='/user/saved-filters'>GO TO SAVED FILTERS</a></li>";
        $output .= "</ul>";
    $output .= "</ul>";
	return $output;
}

function _mnartist_filter_view_filter()
{
	global $user;

	$result = db_query("SELECT mn.title, mn.url FROM {mnartist_filter} mn WHERE mn.uid = :uid", array(':uid' => $user->uid));

	$output = array();
	while ($row = $result->fetchAssoc())
	{
		$output[] = '<a href="' . urldecode($row['url']) . '">' . $row['title'] . '</a>';
	}
	return $output;
}