<?php

/**
 * Implements hook_node_info()
 */
function mn_op_node_info() {
  return array(
    'opportunity' => array(
        'name' => t('Opportunity'),
        'base' => 'node_content',
        'description' => t('Create a new opportunity.'),
        'has_title' => '1',
        'title_label' => t('Opportunity Name'),
     )
  );
}

/**
 * Implements hook_menu().
 *
 */
function mn_op_menu() {
  $items['opportunities'] = array(
    'title' => 'Opportunities',
    'page callback' => 'mn_op_index',
    'access callback' => 'user_is_logged_in',
    'file' => 'mn_op.index.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['applications'] = array(
    'title' => 'Applications',
    'page callback' => 'mn_op_aps',
    'access callback' => 'user_is_logged_in',
    'file' => 'mn_op.applications.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  //path for user to view personal applications for specific opportunities
  $items['application/%'] = array(
    'title' => 'Application',
    'page callback' => 'mn_op_ap',
    'access callback' => 'user_is_logged_in',
    'page arguments' => array(1),
    'file' => 'mn_op.application.inc',
  );

  $items['opportunity/%/jury-settings'] = array(
    'title' => 'Jury Settings',
    'page callback' => 'mn_op_settings',
    'access callback' => 'user_is_logged_in',
    'page arguments' => array(1),
    'file' => 'mn_op.settings.inc',
  );
  return $items;
}

/**
 * Implement hook_form()
 */
function mn_op_form($node, $form_state) {
    return node_content_form($node, $form_state);
}

/**
 * Implements hook_theme().
 */
function mn_op_theme() {
  return array(
    'mn_op_list' => array(
      'variables' => array('rows' => array()),
      'template' => 'mn-op-list',
    ),
    'mn_op_view' => array(
      'variables' => array('rows' => array()),
      'template' => 'mn-op-view',
    ),
    'mn_op_applications' => array(
      'variables' => array('rows' => array()),
      'template' => 'mn-op-applications',
    ),
    'mn_op_application' => array(
      'variables' => array('rows' => array()),
      'template' => 'mn-op-application',
    ),
    'mn_op_settings' => array(
      'variables' => array('rows' => array()),
      'template' => 'mn-op-settings',
    )
  );
}

/**
 * Implements hook_cron().
 * This cron checks announce date and publishes opportunities
 */
function mn_op_cron() {
  // $interval = variable_get('cron_example_interval', 60 * 60);
  $type = "opportunity"; 
  $now = new DateTime();
  $result = NULL;
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $type)
    ->propertyCondition('status', 0);
  $result = $query->execute();
  
  if ($result != NULL) {
    $nodes = node_load_multiple(array_keys($result['node']));
    foreach($nodes as $opportunity) {
      $announce_date = mn_ap_get_comparable_date($opportunity->field_announce_date['und']['0']['value'], $opportunity->field_announce_date['und']['0']['timezone'], $opportunity->field_announce_date['und']['0']['timezone_db']);
      if ($now > $announce_date) {
        $nid = $opportunity->nid;
        $node = node_load($nid);
        $node->status = 1;
        node_save($node);
      }
    }
  }
}

function mn_op_node_view($node, $view_mode, $langcode) {
  // if context user does not own opportunity, or is
  // not an admin, then deny access to node view if
  // current date is prior to announce date
  global $user;
  if ($node->type === 'opportunity') {
    if ($node->uid !== $user->uid && !in_array('administrator', $user->roles)) {
      if (isset($node->field_announce_date[LANGUAGE_NONE])) {
        $now = new DateTime();
        $announce_date = new DateTime($node->field_announce_date[LANGUAGE_NONE][0]['value']);
        if ($now < $announce_date) {
          drupal_access_denied();
          drupal_exit();
        }
      }
    }
  }
}

function mn_op_get_jurors($nid) {
    $result = db_select('op_jurors', 'op')
      ->fields('op')
      ->condition('nid', $nid, '=')
      ->execute()
      ->fetchAll();
    //check for unregistered jurors and update table
    $i = 0;
    foreach ($result as $juror) {
      if ($juror->uid == 0) {
        $checkJuror = mn_op_check_juror_registration($nid, $juror->mail);
        if (isset($checkJuror)) $result = $checkJuror;
      }
      $i++;
    }
    return $result;
}

function mn_op_check_juror_registration($nid, $mail){
  $jurors = '';
  $user = user_load_by_mail($mail);
  if ($user) {
    $juror['uid'] = $user->uid;
    $juror['name'] = $user->name;
    $result = db_update('op_jurors')
      ->condition('nid', $nid, '=')
      ->condition('mail', $mail, '=')
            ->fields($juror)
            ->execute();
        if ($result) $jurors = mn_op_get_jurors($nid);
        return $jurors;
  }
}

function mn_op_check_existing_settings($nid) {
  $result = db_select('op_jury_settings', 'op')
      ->fields('op')
      ->condition('nid', $nid, '=')
      ->execute()
      ->fetchAssoc();
  if (!$result) {
    $result = db_insert('op_jury_settings')
      ->fields(array('nid' => $nid, 'note' => ''))
      ->execute();
  }
  return $result;
}

/*
* convert datetime to correct site db set time
*/
function mn_ap_get_date($date, $timezone, $timezone_db) {
  if($date && $timezone && $timezone_db) {
    $timezone = new DateTimeZone($timezone);
    $timezone_db = new DateTimeZone($timezone_db);

    $resultDate = new DateTime($date, $timezone_db);
    $resultDate->setTimezone($timezone);
    $resultDate = (array) $resultDate;
    $resultDate = new DateTime($resultDate['date']);
    $resultDate = $resultDate->format("M j, Y, g:i a");
  } else {
    $resultDate = '';
  }
  return $resultDate;
}

/*
* convert datetime to correct site db set time in a comparable format
*/
function mn_ap_get_comparable_date($date, $timezone, $timezone_db) {
  if($date && $timezone && $timezone_db) {
    $timezone = new DateTimeZone($timezone);
    $timezone_db = new DateTimeZone($timezone_db);

    $resultDate = new DateTime($date, $timezone_db);
    $resultDate->setTimezone($timezone);
    $resultDate = (array) $resultDate;
    $resultDate = new DateTime($resultDate['date']);
  } else {
    $resultDate = '';
  }
  return $resultDate;
}

/**
 * Implementation of hook_block_info().
 **/
function mn_op_block_info() {
  return array(
      'mna_op_apply_button' => array(
          'info' => 'Opportunity Apply Button',
          'cache' => DRUPAL_NO_CACHE,
          'visibility' => BLOCK_VISIBILITY_PHP
      ),
      'mna_op_external_apply_button' => array(
          'info' => 'Opportunity External Apply Button',
          'cache' => DRUPAL_NO_CACHE,
          'visibility' => BLOCK_VISIBILITY_PHP
      ),
    );
}

/**
 * Implementation of hook_block_view().
 **/
function mn_op_block_view($delta = '') {
    switch($delta) {
        case 'mna_op_apply_button':
            $block['subject'] = 'Opportunity Apply Button';
            $block['content'] = _mn_op_apply_button();
        break;
        case 'mna_op_external_apply_button':
            $block['subject'] = 'Opportunity External Apply Button';
            $block['content'] = _mn_op_external_apply_button();
        break;
    }

    return $block;
}

/* returns html fragment representing apply button on singular opportunity view */
function _mn_op_apply_button() {
  $context_opp = node_load(arg(1));
  $internal = (isset($context_opp-> op_application_type[LANGUAGE_NONE]) && $context_opp-> op_application_type[LANGUAGE_NONE][0]['value'] === '1') ? TRUE : FALSE;
  $start_date = date_create_from_format('Y-n-d G:i:s', $context_opp->op_dates[LANGUAGE_NONE][0]['value']);
  $end_date = date_create_from_format('Y-n-d G:i:s', $context_opp->op_dates[LANGUAGE_NONE][0]['value2']);
  $now = new DateTime();

  if ($internal && $now >= $start_date && $now <= $end_date) {
    $button_fragment_arr = array();
    $button_fragment_arr[] = '<div class="edit-button">';
    if (!user_is_logged_in()) {
      $button_fragment_arr[] = '<a href="/user/login?destination=opportunity/'.$context_opp->nid.'/apply">Apply</a>';
    } else {
      $button_fragment_arr[] = '<a href="/opportunity/'.$context_opp->nid.'/apply">Apply</a>';
    }
    $button_fragment_arr[] = '</div>';
    return implode('', $button_fragment_arr);
  }
}

function _mn_op_external_apply_button() {
  $context_opp = node_load(arg(1));
  $internal = (isset($context_opp-> op_application_type[LANGUAGE_NONE]) && $context_opp-> op_application_type[LANGUAGE_NONE][0]['value'] === '1') ? TRUE : FALSE;
  $start_date = date_create_from_format('Y-n-d G:i:s', $context_opp->op_dates[LANGUAGE_NONE][0]['value']);
  $end_date = date_create_from_format('Y-n-d G:i:s', $context_opp->op_dates[LANGUAGE_NONE][0]['value2']);
  $now = new DateTime();

  $button_fragment_arr = array();
  if (!$internal) {
      if (!empty($context_opp->field_op_uri) && $now >= $start_date && $now <= $end_date) {
          $button_fragment_arr[] = '<a href="'.$context_opp->field_op_uri[LANGUAGE_NONE][0]['value'].'" target="_blank">Apply Here</a>';
      } else {
          $button_fragment_arr[] = 'External Site';
      }
  } else {
      $button_fragment_arr[] = 'MNArtists.org';
  }
  return implode('', $button_fragment_arr);

}