<?php
/**
 * @file
 * Code for the Events Calendar feature.
 */

include_once 'events_calendar.features.inc';

function events_calendar_form_alter(&$form, $form_state, $form_id) {
    if ($form_id === "event_node_form") {
        $form['title']['#title'] = t("Event Title");

        $form['field_url']['und']['#title'] = "";
        $form['field_url']['und'][0]['#title'] = "";

        //hide the community og group field since it gets populated by the user select community field
        if (isset($form['og_group_ref'])) {
            $form['og_group_ref']['#type'] = 'hidden';
        }
    }
}

function events_calendar_node_presave(&$node) {
    // if incoming node is an event...
    if ($node->type === 'event') {
        // overwrite 'old' communities data with data from 'new' communities field
        if (isset($node->field_community_user_select['und'])) {
            $node->og_group_ref['und'] = $node->field_community_user_select['und'];
        }
    }
}